[package]
name = "bunny-plugin"
version = "0.3.0"
edition = "2024"

[features]
default = ["ui"]
ui = ["dep:bunny-ui"]
3d = ["dep:bunny-3d"]
bevy = ["bunny-3d?/bevy"]
tobj = ["bunny-3d?/tobj"]
serde = ["bunny-ui?/serde", "bunny-3d?/serde", "bitflags/serde"]
image = ["bunny-3d?/image"]
manager = []

[dependencies]
abi_stable = "0.11.3"
anyhow = "1.0.104"
bunny-ui = { path = "../bunny-ui", optional = true }
bunny-3d = { path = "../bunny-3d", optional = true }
shared = { path = "../shared" }
ilhook = { version = "2.3.0", features = ["x86"], default-features = false }
tracing-subscriber = "0.3.23"
bitflags = "2.13.1"
