[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[features]
default = []
serde = ["dep:serde"]
manager = []

[dependencies]
anyhow = "1.0.104"
abi_stable = "0.11.3"
rapidhash = "4.5.1"
glam = { version = "0.33.2", features = ["mint"] }
emath = { version = "0.34.3", default-features = false, features = ["mint"] }
mint = "0.5.9"
serde = { version = "1.0.229", features = ["derive"], optional = true }
